### PR TITLE
Layout service

### PR DESCRIPTION
**Pull request by chrishelgert**
* layout-service with [tailor](https://github.com/zalando/tailor)
* changed generated services
* docker-file
* docker-compose

### CODE REVIEW

**Comment by chrishelgert** [comment]
@danielbayerlein it would be great if you could test the docker-compose setup - me docker is currently a little bit buggy :/

**Comment by danielbayerlein** [comment]
@chrishelgert The docker containers can now be started. We still have a problem with the assets.

**Comment by danielbayerlein** [comment]
@chrishelgert Ready for Review?

**Comment by chrishelgert** [comment]
@danielbayerlein yes, everything is working now.
i think we should close this pr at this point.
let´s talk tomorrow about the next steps 😃

**Pull request merged**
