### PR TITLE
script for running the yo-generator over all posible combinations

### PR DESCRIPTION
**Pull request by chrishelgert**
heyho @danielbayerlein ,

i´ve written a script, that should reduce the amount of testing the generated microservices with generator-honeycomb.

one little problem is open, when trying to generate with react, it doesn´t find the linked honeycomb-register-client.

do you maybe know a solution?

### CODE REVIEW

**Comment by danielbayerlein** [comment]
@chrishelgert Good idea! I'm looking for a solution. 🔍

**Comment by danielbayerlein** [comment]
@chrishelgert I found the problem: `npm link` requires a `node_modules`.

The solution:
* Call the yo-generator with the option `--skip-install`
* Call `npm link` after the yo-generator

Tips / Hints:
* `rmdirSync` does not work recursive, see `rimraf`. BTW: Yeoman can update the files if they already exist.
* Add `yo` to the dev-dependencies (`package.json`)
* Does it make sense to put the test-* in a folder (e.g. examples/)?

Thanks for the PR! I hope I could help you.

**Comment by chrishelgert** [comment]
@danielbayerlein  thanks for the tip with skip-install.
now it works.

why rimraf and not updating the existing source: it´s for testing, and i think it is complicated to test a codebase that is complicated overriden/updated, instead of a clean test-instance.

i think example-folder is complecated to handle, while project is wip.
we should keep this in eye when we have a stable release

**Comment by danielbayerlein** [comment]
👍

**Pull request merged**
